accelerate launch train.py  \
    --model_name_or_path google/mt5-small \
    --train_file data/train.jsonl \
    --validation_file data/public.jsonl \
    --output_dir model/batch4 \
    --preprocessing_num_workers 8 \
    --per_device_train_batch_size 4 \
    --num_train_epochs 10 \
    --source_prefix "summarize: " \
    --text_column "maintext" \
    --summary_column "title" \
    --with_tracking