accelerate launch run_qa_em.py \
  --model_name_or_path bert-base-chinese \
  --train_file ../dataset/train.json \
  --validation_file ../dataset/valid.json \
  --context_file ../dataset/context.json \
  --learning_rate 3e-5 \
  --num_train_epochs 2 \
  --max_seq_length 512 \
  --checkpointing_steps 3000 \
  --output_dir ../tmp/debug_squad/ \
  --with_tracking